print("holi")
print("Darling")
print ("Michel")
print("Hola, qué hace?")
print("En clases")
print("Querido diario...")
print("esta es mi tercera vez")
print("Erase una vez...")
print("En un mundo, muy, muy lejano")
print("ya me dio pereza seguir")
print("Fin")
print("estamos jodidos jajajaja")
print("Hola, estoy en mi nueva rama")
